# Generated by Django 5.0.1 on 2024-02-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=256, null=True)),
                ('institucion', models.CharField(blank=True, max_length=256, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('archivos', models.FileField(blank=True, max_length=255, null=True, upload_to='archivos/%Y/%m/%d/', verbose_name='Archivos')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
